FROM node:22.15.0-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl && \
    rm -rf /var/lib/apt/lists/*


# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 4500

# Run the app
CMD [ "npm","run","start" ]

