services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    container_name: next_service
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./next:/usr/src/app
      - next_node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: ${NODE_ENV:-development}

  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile
    container_name: nest_service
    working_dir: /usr/src/app
    ports:
      - "4500:4500"
    volumes:
      - ./nest:/usr/src/app
      - nest_node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  next_node_modules:
  nest_node_modules:
  mongodb-data:
